export const VISA_PRICING = {
  usa: {
    label: "États-Unis",
    flag: "🇺🇸",
    engagementFee: 250,
    successFee: 750,
    total: 1000,
    successModel: "appointment" as const,
    visaTypes: ["B1/B2 (Tourisme/Affaires)", "F1 (Étudiant)", "K1 (Fiancé(e))", "H1B (Travail)", "J1 (Échange)"],
    requiredDocuments: [
      { key: "passport_scan", label: "Passeport (scan HD)", required: true },
      { key: "photo_id", label: "Photo d'identité 5x5 fond blanc", required: true },
      { key: "proof_of_funds", label: "Relevés bancaires (3 derniers mois)", required: true },
      { key: "employment_letter", label: "Attestation de travail / RCCM", required: true },
      { key: "ds160_confirmation", label: "Confirmation DS-160", required: true },
      { key: "mrv_receipt", label: "Reçu paiement MRV (265$)", required: true },
    ],
    embassyAddress: "502 Gombe, Kinshasa, Ambassade des États-Unis",
    portalUrl: "https://www.usvisaappt.com/visaapplicantui/login",
    portalName: "AVITS / VISAPP (usvisaappt.com)",
    portalDashboardUrl: "https://www.usvisaappt.com/visaapplicantui/home/dashboard/requests",
    portalAppointmentUrl: "https://www.usvisaappt.com/visaapplicantui/home/appointment/myappointment",
    portalScheduleUrl: "https://www.usvisaappt.com/visaapplicantui/home/dashboard/Appointment-scheduled",
    apiBaseUrl: "https://www.usvisaappt.com/visauserapi",
    apiAdminBaseUrl: "https://www.usvisaappt.com/visaadministrationapi/v1",
    apiAuthProvider: "aws-cognito",
    apiUserProfileEndpoint: "/portal/getuser",
    apiAppointmentsEndpoint: "/portal/getappointments",
    apiAppointmentRequestsEndpoint: "/appointmentrequest/getallbyuser",
    missionId: 323,
    appointmentStatusCodes: {
      pendingPayment: 2,
      scheduled: 1,
      cancelled: 0,
    },
    processingType: "appointment",
    successCopy: {
      triggerLabel: "Créneau capturé",
      clientCtaTitle: "Créneau trouvé !",
      clientCtaBody: "Joventy a verrouillé un rendez-vous à l'ambassade. Réglez la prime de succès pour recevoir le PDF de confirmation officiel (indispensable pour l'entretien).",
      completedNote: "Téléchargez votre kit d'entretien complet ci-dessous.",
    },
    notes: "Les frais consulaires MRV (265$) sont payés séparément par le client directement à la banque.",
  },
  canada: {
    label: "Canada",
    flag: "🇨🇦",
    engagementFee: 250,
    successFee: 750,
    total: 1000,
    successModel: "appointment" as const,
    visaTypes: [
      "Biométrie (Biometric Enrolment)",
      "Visa Visiteur (Tourisme / Affaires)",
      "Permis d'études (Study Permit)",
      "Permis de travail (Work Permit)",
      "Résidence Permanente (PR)",
    ],
    requiredDocuments: [
      { key: "passport_scan", label: "Passeport valide (scan HD, 2 pages bio)", required: true },
      { key: "photo_id", label: "Photo d'identité fond blanc (35×45 mm)", required: true },
      { key: "proof_of_funds", label: "Relevés bancaires (3 derniers mois)", required: true },
      { key: "employment_letter", label: "Attestation de travail / RCCM", required: true },
      { key: "invitation_letter", label: "Lettre d'invitation ou réservation hôtel", required: false },
      { key: "biometric_letter", label: "Lettre de collecte biométrique IRCC (si applicable)", required: false },
    ],
    embassyAddress: "VFS Global IRCC — Centre de Collecte Biométrique, Kinshasa-Gombe",
    portalUrl: "https://www.vfsglobal.ca/IRCC-AppointmentWave1/Account/Login",
    portalName: "VFS Global IRCC Canada (IRCC-AppointmentWave1)",
    portalDashboardUrl: "https://www.vfsglobal.ca/IRCC-AppointmentWave1/Home/Index",
    portalAppointmentUrl: "https://www.vfsglobal.ca/IRCC-AppointmentWave1/Home/SelectVAC",
    portalScheduleUrl: "https://www.vfsglobal.ca/IRCC-AppointmentWave1/Home/SelectVAC",
    processingType: "appointment",
    successCopy: {
      triggerLabel: "Créneau VFS IRCC capturé",
      clientCtaTitle: "Créneau Canada trouvé !",
      clientCtaBody: "Joventy a verrouillé un rendez-vous au centre VFS IRCC de Kinshasa. Réglez la prime de succès pour recevoir votre convocation officielle avec la date, l'heure et les instructions de présentation.",
      completedNote: "Votre convocation VFS IRCC est disponible ci-dessous — présentez-la le jour du rendez-vous avec vos documents originaux.",
    },
    notes: "Les frais de service IRCC (85 CAD pour la biométrie, variable selon le type de visa) sont payés séparément par le client directement à Immigration Canada. Le rendez-vous biométrique est obligatoire pour toute première demande de visa canadien.",
  },
  uk: {
    label: "Royaume-Uni",
    flag: "🇬🇧",
    engagementFee: 200,
    successFee: 600,
    total: 800,
    successModel: "appointment" as const,
    visaTypes: [
      "Standard Visitor Visa",
      "Student Visa",
      "Work Visa (Skilled Worker)",
      "Family / Spouse Visa",
      "Transit Visa",
    ],
    requiredDocuments: [
      { key: "passport_scan", label: "Passeport valide (scan HD, 2 pages bio)", required: true },
      { key: "photo_id", label: "Photo d'identité fond blanc (35×45 mm)", required: true },
      { key: "proof_of_funds", label: "Relevés bancaires (6 derniers mois)", required: true },
      { key: "employment_letter", label: "Attestation de travail / RCCM / lettre d'inscription", required: true },
      { key: "travel_insurance", label: "Assurance voyage", required: false },
      { key: "invitation_letter", label: "Lettre d'invitation (si hébergement chez un tiers)", required: false },
      { key: "hotel_booking", label: "Réservation hôtel confirmée", required: false },
      { key: "flight_booking", label: "Réservation de vol (confirmée)", required: false },
    ],
    embassyAddress: "VFS Global UKVI — Centre de dépôt, Kinshasa-Gombe",
    portalUrl: "https://visa.vfsglobal.com/cod/en/gbr/login",
    portalName: "VFS Global UK Visas & Immigration (COD → GBR)",
    portalDashboardUrl: "https://visa.vfsglobal.com/cod/en/gbr/application-detail",
    portalAppointmentUrl: "https://visa.vfsglobal.com/cod/en/gbr/book-an-appointment",
    portalScheduleUrl: "https://visa.vfsglobal.com/cod/en/gbr/book-an-appointment",
    processingType: "appointment",
    successCopy: {
      triggerLabel: "Créneau VFS UKVI capturé",
      clientCtaTitle: "Créneau Royaume-Uni trouvé !",
      clientCtaBody: "Joventy a verrouillé un rendez-vous au centre VFS UKVI de Kinshasa. Réglez la prime de succès pour recevoir votre convocation officielle avec la date, l'heure et les instructions de dépôt.",
      completedNote: "Votre convocation VFS UKVI est disponible ci-dessous — présentez-la le jour du rendez-vous avec vos documents originaux.",
    },
    notes: "Les frais UKVI (UK Visas & Immigration) sont payés séparément par le client : £115 Standard Visitor, £490 Student, variable selon le type. Délai de traitement : 3 semaines (standard) ou 5 jours ouvrables (prioritaire). Biométrie collectée au centre VFS Global.",
  },
  switzerland: {
    label: "Suisse",
    flag: "🇨🇭",
    engagementFee: 150,
    successFee: 450,
    total: 600,
    successModel: "appointment" as const,
    visaTypes: [
      "Visa C — Tourisme / Affaires (Schengen)",
      "Visa C — Études court séjour",
      "Transit aéroportuaire",
    ],
    requiredDocuments: [
      { key: "passport_scan", label: "Passeport valide (scan HD, 2 pages bio)", required: true },
      { key: "photo_id", label: "Photo d'identité 3,5×4,5 cm fond blanc (JPEG < 100 kb)", required: true },
      { key: "proof_of_funds", label: "Relevés bancaires (3 derniers mois)", required: true },
      { key: "employment_letter", label: "Attestation de travail / RCCM / certificat de scolarité", required: true },
      { key: "travel_insurance", label: "Assurance voyage Schengen (min. 30 000 €)", required: true },
      { key: "hotel_booking", label: "Réservation hôtel ou attestation d'hébergement", required: true },
      { key: "flight_booking", label: "Billets d'avion (réservation confirmée)", required: true },
      { key: "invitation_letter", label: "Lettre d'invitation / convocation (si applicable)", required: false },
    ],
    embassyAddress: "VFS Global Suisse — Centre de collecte, Kinshasa-Gombe",
    portalUrl: "https://visa.vfsglobal.com/cod/en/che/login",
    portalName: "VFS Global Suisse (COD → CHE)",
    portalDashboardUrl: "https://visa.vfsglobal.com/cod/en/che/application-detail",
    portalAppointmentUrl: "https://visa.vfsglobal.com/cod/en/che/book-an-appointment",
    portalScheduleUrl: "https://visa.vfsglobal.com/cod/en/che/book-an-appointment",
    processingType: "appointment",
    successCopy: {
      triggerLabel: "Créneau VFS Suisse capturé",
      clientCtaTitle: "Créneau Suisse trouvé !",
      clientCtaBody: "Joventy a verrouillé un rendez-vous au centre VFS Global Suisse de Kinshasa. Réglez la prime de succès pour recevoir votre convocation officielle.",
      completedNote: "Votre convocation VFS Suisse est disponible ci-dessous — présentez-la le jour du rendez-vous.",
    },
    notes: "Visa Schengen court séjour (Visa C ≤ 90 jours) délivré par l'Ambassade de Suisse via VFS Global Kinshasa. Frais consulaires payés séparément : 90 € adulte. Délai légal : 15 jours ouvrables. Le Visa D (long séjour > 90 jours) est traité directement à l'ambassade — non pris en charge par Joventy actuellement.",
  },
  dubai: {
    label: "Dubaï (EAU)",
    flag: "🇦🇪",
    engagementFee: 80,
    successFee: 120,
    total: 200,
    successModel: "evisa" as const,
    visaTypes: ["Touriste 30j", "Touriste 60j", "Résidence", "Affaires"],
    requiredDocuments: [
      { key: "passport_scan", label: "Passeport (scan HD)", required: true },
      { key: "photo_id", label: "Photo d'identité fond blanc (JPEG < 100kb)", required: true },
      { key: "travel_dates", label: "Billets d'avion (réservation)", required: true },
      { key: "hotel_booking", label: "Réservation hôtel confirmée", required: false },
    ],
    embassyAddress: "Portail GDRFA / ICP — 100% électronique",
    portalUrl: "https://visa.vfsglobal.com/cod/en/are",
    portalName: "VFS Global — Visa Émirats (COD → ARE)",
    portalDashboardUrl: "https://visa.vfsglobal.com/cod/en/are/application-detail",
    portalAppointmentUrl: "https://visa.vfsglobal.com/cod/en/are/book-an-appointment",
    portalScheduleUrl: "https://visa.vfsglobal.com/cod/en/are/book-an-appointment",
    processingType: "evisa",
    successCopy: {
      triggerLabel: "Visa obtenu",
      clientCtaTitle: "Votre visa est prêt !",
      clientCtaBody: "Les autorités des Émirats ont accordé votre visa électronique. Réglez la prime de succès pour recevoir votre e-Visa PDF prêt à imprimer.",
      completedNote: "Votre visa électronique est disponible ci-dessous — prêt à imprimer avant le départ.",
    },
    notes: "E-Visa 100% électronique. Résultat en 48-72h ouvrables. Les frais gouvernementaux e-Visa EAU (~90$) sont payés séparément par le client.",
  },
  turkey: {
    label: "Turquie",
    flag: "🇹🇷",
    engagementFee: 80,
    successFee: 120,
    total: 200,
    successModel: "appointment" as const,
    visaTypes: ["E-Visa (si visa USA/Schengen)", "Visa Sticker (VFS Kinshasa)"],
    requiredDocuments: [
      { key: "passport_scan", label: "Passeport (scan HD)", required: true },
      { key: "photo_id", label: "Photo d'identité", required: true },
      { key: "bank_statements", label: "Relevés bancaires (3 derniers mois)", required: true },
      { key: "employment_letter", label: "Certificat de travail / RCCM", required: true },
      { key: "hotel_booking", label: "Réservation hôtel confirmée (normes turques)", required: true },
      { key: "travel_insurance", label: "Assurance voyage (normes turques)", required: true },
    ],
    embassyAddress: "VFS Global — Avenue de la Gombe, Kinshasa",
    portalUrl: "https://visa.vfsglobal.com/cod/en/tur",
    portalName: "VFS Global Turquie (COD → TUR)",
    portalDashboardUrl: "https://visa.vfsglobal.com/cod/en/tur/application-detail",
    portalAppointmentUrl: "https://visa.vfsglobal.com/cod/en/tur/book-an-appointment",
    portalScheduleUrl: "https://visa.vfsglobal.com/cod/en/tur/book-an-appointment",
    processingType: "hybrid",
    successCopy: {
      triggerLabel: "Créneau VFS capturé",
      clientCtaTitle: "Créneau VFS trouvé !",
      clientCtaBody: "Joventy a réservé un créneau au centre de dépôt VFS Global. Réglez la prime de succès pour recevoir votre convocation de dépôt.",
      completedNote: "Votre convocation VFS et les instructions de dépôt sont disponibles ci-dessous.",
    },
    notes: "E-Visa uniquement si le client possède déjà un visa USA ou Schengen valide. Sinon : Visa Sticker via VFS. Les frais consulaires (100$ entrée unique / 300$ multi-entrées) et frais VFS sont payés séparément par le client.",
  },
  india: {
    label: "Inde",
    flag: "🇮🇳",
    engagementFee: 100,
    successFee: 150,
    total: 250,
    successModel: "evisa" as const,
    visaTypes: ["e-Visa Touriste", "Médical (e-Medical)", "Études (Regular Visa)"],
    requiredDocuments: [
      { key: "passport_scan", label: "Passeport (scan HD)", required: true },
      { key: "photo_id", label: "Photo d'identité fond blanc", required: true },
      { key: "invitation_letter", label: "Lettre d'invitation (hôpital/université)", required: true },
      { key: "proof_of_funds", label: "Relevés bancaires", required: true },
      { key: "medical_recommendation", label: "Lettre de recommandation médecin RDC (Médical)", required: false },
    ],
    embassyAddress: "Ambassade de l'Inde — Avenue de la Gombe, Kinshasa",
    portalUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
    portalName: "Indian Visa Online (e-Visa Inde)",
    portalDashboardUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
    portalAppointmentUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
    portalScheduleUrl: "https://indianvisaonline.gov.in/evisa/StatusEnquiry.html",
    processingType: "evisa",
    successCopy: {
      triggerLabel: "E-Visa obtenu",
      clientCtaTitle: "Votre e-Visa Inde est prêt !",
      clientCtaBody: "Le gouvernement indien a accordé votre e-Visa. Réglez la prime de succès pour recevoir votre document officiel à imprimer avant l'embarquement.",
      completedNote: "Votre e-Visa Inde est disponible ci-dessous — à imprimer et présenter à l'embarquement.",
    },
    notes: "Pour le Médical : vérification accréditation hôpital incluse. Pour les Études longue durée : entretien physique à l'Ambassade possible. Les frais e-Visa gouvernement indien (~25-80$ selon durée) sont payés séparément par le client.",
  },
  spain: {
    label: "Espagne",
    flag: "🇪🇸",
    engagementFee: 150,
    successFee: 450,
    total: 600,
    successModel: "appointment" as const,
    visaTypes: [
      "Visa C — Tourisme / Affaires",
      "Visa C — Études court séjour",
    ],
    requiredDocuments: [
      { key: "passport_scan", label: "Passeport valide (scan HD, 2 pages bio)", required: true },
      { key: "photo_passport_selfie", label: "Photo de vous à côté de votre passeport ouvert (JPEG/PDF, lisible) — pour inscription email", required: true },
      { key: "photo_id", label: "Photo d'identité 3,5×4,5 cm fond blanc (JPEG < 100 kb)", required: true },
      { key: "application_form", label: "Formulaire de candidature officiel (avec photo)", required: true },
      { key: "flight_booking", label: "Réservation de vol (confirmée)", required: true },
      { key: "travel_insurance", label: "Assurance santé / voyage Schengen (min. 30 000 €)", required: true },
      { key: "proof_of_funds", label: "Relevés bancaires (3 derniers mois)", required: true },
      { key: "employment_letter", label: "Attestation de travail / RCCM / certificat de scolarité", required: true },
      { key: "hotel_booking", label: "Réservation hôtel ou attestation d'hébergement", required: true },
      { key: "invitation_letter", label: "Lettre d'invitation / convocation (si applicable)", required: false },
    ],
    embassyAddress: "Ambassade d'Espagne — Avenue des Trois Z, Kinshasa-Gombe",
    embassyEmail: "emb.kinshasa.citasvis@maec.es",
    embassyEmailSubject: "RENDEZ-VOUS VISA EST",
    trackingUrl: "https://sutramiteconsular.maec.es/Home.aspx",
    portalUrl: "https://www.citaconsular.es/es/hosteds/widgetdefault/25028fcd7126544630b8da0c6e60722b5",
    portalName: "Cita Consular — Ambassade Espagne Kinshasa",
    portalDashboardUrl: "https://www.citaconsular.es/es/hosteds/widgetdefault/25028fcd7126544630b8da0c6e60722b5",
    portalAppointmentUrl: "https://www.citaconsular.es/es/hosteds/widgetdefault/25028fcd7126544630b8da0c6e60722b5",
    portalScheduleUrl: "https://www.citaconsular.es/es/hosteds/widgetdefault/25028fcd7126544630b8da0c6e60722b5",
    processingType: "appointment",
    successCopy: {
      triggerLabel: "Créneau capturé",
      clientCtaTitle: "Créneau Espagne trouvé !",
      clientCtaBody: "Joventy a verrouillé un rendez-vous à l'ambassade d'Espagne. Réglez la prime de succès pour recevoir votre convocation officielle avec la date, l'heure et les instructions de dépôt.",
      completedNote: "Votre convocation consulaire espagnole est disponible ci-dessous — présentez-la le jour du rendez-vous.",
    },
    notes: "Visa Schengen court séjour (Visa C ≤ 90 jours) uniquement. Le Visa D long séjour est traité directement à l'ambassade — non pris en charge par Joventy actuellement. Procédure en 2 étapes : (1) Inscription par email à emb.kinshasa.citasvis@maec.es (objet : RENDEZ-VOUS VISA EST) avec photo+passeport, formulaire, réservation vol et assurance santé — l'ambassade envoie un identifiant/mot de passe. (2) Prise de RDV sur citaconsular.es avec ces identifiants. Frais consulaires espagnols (90 € adulte) payés directement à l'ambassade. Délai légal : 15 à 45 jours. Demande entre 6 mois et 15 jours avant le voyage.",
  },
  schengen: {
    label: "Europe Schengen",
    flag: "🇪🇺",
    engagementFee: 150,
    successFee: 450,
    total: 600,
    successModel: "appointment" as const,
    visaTypes: [
      "Visa C — Tourisme / Affaires",
      "Visa C — Études court séjour (gratuit*)",
    ],
    requiredDocuments: [
      { key: "passport_scan", label: "Passeport valide (scan HD, 2 pages bio)", required: true },
      { key: "photo_id", label: "Photo d'identité 3,5×4,5 cm fond blanc (JPEG < 100 kb)", required: true },
      { key: "proof_of_funds", label: "Relevés bancaires (3 derniers mois)", required: true },
      { key: "employment_letter", label: "Attestation de travail / RCCM / certificat de scolarité", required: true },
      { key: "travel_insurance", label: "Assurance voyage Schengen (min. 30 000 €)", required: true },
      { key: "hotel_booking", label: "Réservation hôtel ou attestation d'hébergement", required: true },
      { key: "flight_booking", label: "Billets d'avion (réservation confirmée)", required: true },
      { key: "invitation_letter", label: "Lettre d'invitation / convocation (si applicable)", required: false },
    ],
    embassyAddress: "Centre Européen des Visas (CEV) — Avenue des Aviateurs, Kinshasa-Gombe",
    portalUrl: "https://appointment.cloud.diplomatie.be/",
    portalName: "CEV Kinshasa — diplomatie.be (17 pays Schengen)",
    portalDashboardUrl: "https://visaonweb.diplomatie.be/fowint/",
    portalAppointmentUrl: "https://appointment.cloud.diplomatie.be/Captcha",
    portalScheduleUrl: "https://appointment.cloud.diplomatie.be/Home/AvailableTimeSlots",
    processingType: "appointment",
    successCopy: {
      triggerLabel: "Créneau CEV capturé",
      clientCtaTitle: "Créneau Schengen trouvé !",
      clientCtaBody: "Joventy a verrouillé un rendez-vous au Centre Européen des Visas. Réglez la prime de succès pour recevoir votre convocation officielle avec date, heure et lieu.",
      completedNote: "Votre convocation CEV est disponible ci-dessous — présentez-la le jour du rendez-vous.",
    },
    notes: "Visa C court séjour (≤ 90 jours) uniquement — le Visa D long séjour est traité directement à l'ambassade compétente et n'est pas pris en charge par Joventy actuellement. Frais consulaires CEV (handling fee) payés en € par carte bancaire au guichet, NON inclus dans les frais Joventy. Visa C adulte : 90 €. Enfant 6-12 ans : 45 €. Moins de 6 ans : gratuit. Étudiants/chercheurs visa C court séjour : gratuit.",
  },
} as const;

export type Destination = keyof typeof VISA_PRICING;
export type SuccessModel = "appointment" | "evisa";
export type ServicePackage = "full_service" | "slot_only" | "dossier_only";

export const SLOT_URGENCY_TIERS = {
  standard: {
    key: "standard" as const,
    label: "Standard",
    tagline: "> 3 mois",
    desc: "Date souhaitée dans plus de 3 mois",
    depositAmount: 80,
    successAmount: 170,
    total: 250,
    variableNote: null,
  },
  prioritaire: {
    key: "prioritaire" as const,
    label: "Prioritaire",
    tagline: "1 à 3 mois",
    desc: "Date souhaitée dans 1 à 3 mois",
    depositAmount: 120,
    successAmount: 230,
    total: 350,
    variableNote: null,
  },
  urgent: {
    key: "urgent" as const,
    label: "Urgent",
    tagline: "3 à 6 semaines",
    desc: "Date souhaitée dans 3 à 6 semaines",
    depositAmount: 150,
    successAmount: 300,
    total: 450,
    variableNote: null,
  },
  tres_urgent: {
    key: "tres_urgent" as const,
    label: "Très Urgent",
    tagline: "< 3 semaines / ASAP",
    desc: "Date souhaitée dans moins de 3 semaines ou dès que possible",
    depositAmount: 200,
    successAmount: 400,
    total: 600,
    variableNote: "Prime indicative — peut dépasser 600 $ selon disponibilité. Confirmée par Joventy.",
  },
} as const;

export type SlotUrgencyTier = keyof typeof SLOT_URGENCY_TIERS;

export const SERVICE_PACKAGES = {
  full_service: {
    key: "full_service" as const,
    label: "Service Complet",
    tagline: "Recommandé",
    description: "Joventy remplit les formulaires officiels, vérifie les pièces que vous fournissez et gère la recherche de créneau ou la soumission du visa électronique.",
    hasSuccessFee: true,
    availableFor: "all" as const,
  },
  slot_only: {
    key: "slot_only" as const,
    label: "Créneau Uniquement",
    tagline: "Dossier prêt",
    description: "Vos formulaires sont remplis et vos pièces prêtes ? Joventy se concentre uniquement sur l'obtention d'un créneau de rendez-vous consulaire.",
    hasSuccessFee: true,
    availableFor: ["usa", "canada", "uk", "switzerland", "turkey", "schengen", "spain"] as const,
  },
  dossier_only: {
    key: "dossier_only" as const,
    label: "Formulaires & Vérification",
    tagline: "Tarif fixe",
    description: "Joventy remplit les formulaires requis et vérifie les pièces que vous fournissez. Vous gérez ensuite votre rendez-vous ou soumission de façon autonome. Tarif fixe.",
    hasSuccessFee: false,
    availableFor: "all" as const,
  },
} as const;

export function getAvailablePackages(destination: string): ServicePackage[] {
  const result: ServicePackage[] = ["full_service", "dossier_only"];
  const slotPkg = SERVICE_PACKAGES.slot_only;
  if ((slotPkg.availableFor as readonly string[]).includes(destination)) {
    result.splice(1, 0, "slot_only");
  }
  return result;
}

export const APPLICATION_STATUSES = {
  awaiting_engagement_payment: {
    label: "En attente de paiement",
    description: "Frais d'engagement à régler pour activer le dossier",
    color: "orange",
    step: 1,
  },
  documents_pending: {
    label: "Documents requis",
    description: "Veuillez uploader vos documents dans le coffre-fort",
    color: "blue",
    step: 2,
  },
  in_review: {
    label: "En traitement",
    description: "Votre dossier est en cours d'examen par Joventy",
    color: "blue",
    step: 3,
  },
  slot_hunting: {
    label: "En cours de traitement",
    description: "Notre équipe travaille activement sur votre dossier",
    color: "purple",
    step: 3,
  },
  slot_found_awaiting_success_fee: {
    label: "Résultat obtenu !",
    description: "Réglez la prime de succès pour débloquer votre document",
    color: "green",
    step: 4,
  },
  completed: {
    label: "Dossier complété",
    description: "Votre document est disponible — félicitations !",
    color: "green",
    step: 5,
  },
  rejected: {
    label: "Dossier rejeté",
    description: "Votre dossier n'a pas pu être traité",
    color: "red",
    step: 0,
  },
} as const;

export type ApplicationStatus = keyof typeof APPLICATION_STATUSES;

export const MOBILE_MONEY_INFO = {
  mpesa: { name: "M-Pesa", number: "0820 344 541", instructions: "Envoyez le montant exact au numéro ci-dessus, puis uploadez la capture d'écran du reçu." },
  airtel: { name: "Airtel Money", number: "0990 775 880", instructions: "Envoyez le montant exact au numéro ci-dessus, puis uploadez la capture d'écran du reçu." },
  orange: { name: "Orange Money", number: "+243 840 808 122", instructions: "Envoyez le montant exact au numéro ci-dessus, puis uploadez la capture d'écran du reçu." },
};
